//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHoldPart.Model.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DocumentEmployee
    {
        public string Path { get; set; }
        public int DocumentId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
       
        public string EmployeeName
        {
            get
            {
                using (var context = new HouseholdPartEntities())
                {
                    var a = context.Employee.Where(x => x.EmployeeId == EmployeeId)?.FirstOrDefault();
                    return a?.NameEmployee + " " + a?.SurnameEmployee;
                }
            }
        }
        public string DocumentName { get; set; }
        public string Documents { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
