//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHoldPart.Model.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.DocumentEmployee = new HashSet<DocumentEmployee>();
            this.ScheduleEmployee = new HashSet<ScheduleEmployee>();
        }
    
        public int EmployeeId { get; set; }
        public string NameEmployee { get; set; }
        public string SurnameEmployee { get; set; }
        public Nullable<int> IdPost { get; set; }
        public string PostName
        {
            get
            {
                using (var context = new HouseholdPartEntities())
                {
                    var a = context.Post.Where(x => x.PostId == IdPost).FirstOrDefault();
                    return a.PostName;
                }
            }
        }
        public Nullable<int> SerialPasportEmployee { get; set; }
        public Nullable<int> NumberPasportEmployee { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentEmployee> DocumentEmployee { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleEmployee> ScheduleEmployee { get; set; }
    }
}
