//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHoldPart.Model.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Equipment
    {
        public int EquipmentId { get; set; }
        public string NameEquipment { get; set; }
        public int Count { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> IdFacilities { get; set; }
        public Nullable<int> IdSuppliers { get; set; }

        public string FacilitiesName
        {
            get
            {
                {
                    using (var context = new HouseholdPartEntities())
                    {
                        var a = context.Facilities.Where(x => x.FacilitiesId == IdFacilities)?.FirstOrDefault();
                        return a.NameFacilities;
                    }
                }
            }
        }
        public string SuppliersName
        {
            get
            {
                {
                    using (var context = new HouseholdPartEntities())
                    {
                        var a = context.Suppliers.Where(x => x.SupplierId == IdSuppliers)?.FirstOrDefault();
                        return a.NameSupplier;
                    }
                }
            }
        }
        public virtual Facilities Facilities { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
