//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHoldPart.Model.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ScheduleEmployee
    {
        public int ScheduleId { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string EmployeeName
        {
            get
            {
                using (var context = new HouseholdPartEntities())
                {
                    var a = context.Employee.Where(x => x.EmployeeId == IdEmployee)?.FirstOrDefault();
                    return a?.SurnameEmployee + " " + a?.NameEmployee;
                }
            }
	        }

        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
